#!/usr/bin/env bash

# shellcheck source=/dev/null
source "$HOME/.config/backup/shared_setup.bash"

# shellcheck disable=2154
PASSPHRASE="$(cat "$passphrase_file")" \
  duplicity \
  collection-status \
  "$backup_url"
