# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json
- name: Rust
  tags: rust
  block:
    - name: Install rustup
      become: true
      package:
        name: rustup
        state: present

    - name: Install Rust stable
      become_user: mange
      command: rustup install stable
      args:
        creates: /home/mange/.local/share/rustup/toolchains/stable-x86_64-unknown-linux-gnu

    - name: Installing Rust components
      shell: |
        rustup component add rust-src
        rustup component add clippy
        rustup component add rust-analysis
        rustup component add rustfmt

    - name: Installing Rust crates
      shell: |
        cargo install cargo-update
        cargo install cargo-edit
        cargo install cargo-watch

    - name: Installing Rust updates
      tags: install-updates
      shell: |
        cargo install-update --all
