FROM archlinux:base
RUN pacman -Syu --noconfirm

# Let some of the scripts be able to detect this case to avoid crashing on
# things that are not possible inside the container (for example: dealing with
# systemd).
ENV INSIDE_DOCKER=1

# Install the bootstrap dependencies first to make the script quicker to run
# while iterating.
RUN pacman -Sy && \
  pacman -S --needed --noconfirm \
  sudo ansible curl zsh

# Prevent ZSH newuser prompt everytime a new testing container is started.
RUN rm /usr/share/zsh/scripts/newuser

# Let wheel users run all sudo things without a password to make testing simpler.
# (As you cannot log in as root to set a password for the mange user)
RUN echo "%wheel ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/wheel-passwordless

COPY --chown=root:root ./bootstrap/bootstrap.sh /root/bootstrap.sh
COPY --chown=root:root ./bootstrap/bootstrap.yml /root/bootstrap.yml
RUN /root/bootstrap.sh

CMD zsh

# Now run the rest of the setup as mange
USER mange
WORKDIR /home/mange
