#!/usr/bin/env zsh
# Editor settings

try-editor () {
  if which $1 >/dev/null; then
    EDITOR="$@"
  fi
}

try-editor nano
try-editor vi
try-editor vim
[[ $DISPLAY != "" ]] && try-editor gvim -f
try-editor mvim -f --nomru

export VISUAL=$EDITOR

unset try-editor
