#!/bin/zsh
# Aliases
# First of all, we have ordinary aliases
# Then we have inline aliases

alias j='jobs'

alias ls='ls --color=auto -h'
alias lsl='ls -l'
alias lsa='ls -a'
alias l='ls -la'

# Give less more advanced capabilities, like coloring, save to file, etc.
if [[ -f /usr/share/vim/current/macros/less.sh ]]; then
  alias less='/usr/share/vim/current/macros/less.sh'
fi

alias cwd='pwd'

alias po='popd'
alias pd='pushd'

##########################################################################################
# Older versions of grep does not understand --exclude-dir. Do not set if older version...
minor=$(  command grep --version | grep -E "[0-9]+\.[0-9]+\.[0-9]+" | awk -F '.' '{ print $3 }')
release=$(command grep --version | grep -E "[0-9]+\.[0-9]+\.[0-9]+" | awk -F '.' '{ print $2 }')

if [[ $minor > 5 || ( $minor == 5 && $release > 1 ) ]]; then
  alias grep='grep --color=auto --exclude-dir=.svn --exclude-dir=.git'
else
  alias grep='grep --color=auto'
fi
##########################################################################################

alias findtext='grep -r . -e'
alias textgrep='findtext'

alias isomount='mount -o loop -t iso9660'

alias cp='cp -i' # Confirm before overwriting

################################################################
# SVN and git aliases
#
alias sst='svn status'
alias sco='svn commit'
alias sup='svn update'
alias sdf='svn diff'
alias sdiff='svn diff'
alias slog='svn log'

alias gst='git status'
alias gco='git commit -v'
alias gup='git pull'
alias gdf='git diff'
alias gdiff='git diff'
alias glog='git log'
alias grst='git reset'
alias branches='git branches -a'
alias checkout='git checkout'
alias gch='git checkout'
alias gadd='git add'
alias gad='git add'
alias dcommit='git svn dcommit'
alias drebase='git svn rebase'

################################################################
# Ruby on Rails aliases
alias sc='script/console'

################################################################
# Inline aliases

# cd by .. or ... or ... or mv file ..../.
alias '..'='cd ..'
alias -g '...'='../..'
alias -g '....'='../../..'
alias -g '.....'='../../../..'

alias -g '..2'='../..'
alias -g '..3'='../../..'
alias -g '..4'='../../../..'
alias -g '..5'='../../../../..'

alias -g E='| `echo $EDITOR`' # Lazy evaluation so we're not locking this alias the the $EDITOR defined during the initialization
alias -g G='| grep'
alias -g S='| sed'
alias -g L='| less'
alias -g LL="2>&1 | less"

alias -g HL="--help"
alias -g NE="2> /dev/null"
alias -g NUL="> /dev/null 2>&1"

# Newest File and Newest Directory
# Example of use:
#    dmesg > log
#    mkdir status
#    cp NF ND
#
alias -g ND='$(ls -d *(/om[1]))' # newest directory
alias -g NF='$(ls *(.om[1]))'    # newest file

# Resume screen
alias -g SC='screen -R'
