#!/bin/zsh

alias j='jobs'
alias cwd='pwd'
alias po='popd'
alias pd='pushd'

alias ls='ls --color=auto -h'
alias lsl='ls -l'
alias lsa='ls -a'
alias l='ls -la'

alias cp='cp -i'

command_exists ack-grep && alias ack='ack-grep' # Debian

# Give less more advanced capabilities like coloring
if [[ -f /usr/share/vim/current/macros/less.sh ]]; then
  alias less='/usr/share/vim/current/macros/less.sh'
fi

# Helpful commands
alias isomount='mount -o loop -t iso9660'

# Copy / Paste
command_exists pbcopy  || alias pbcopy='xsel --clipboard --input'
command_exists pbpaste || alias pbpaste='xsel --clipboard --output'

# SVN
alias sst='svn status'
alias sco='svn commit'
alias sup='svn update'
alias sdf='svn diff'
alias sdiff='svn diff'
alias slog='svn log'

# Git
alias branches='git branches -a'
alias checkout='git checkout'
alias dcommit='git svn dcommit'
alias drebase='git svn rebase'
alias gad='git add'
alias gadd='git add'
alias gap='git add -p'
alias gch='git checkout'
alias gco='git commit -v'
alias gdf='git diff'
alias gdiff='git diff'
alias ggraph='git log --all --decorate --graph --pretty=oneline --abbrev-commit'
alias glog='git log'
alias gm='git merge'
alias gmo='git merge origin/master'
alias gpl='git pull --rebase'
alias gpu='git push'
alias gr='git rebase'
alias gri='git rebase -i'
alias gro='git rebase origin/master'
alias grs='git reset'
alias grst='git reset'
alias gst='git status'
alias gup='git fetch'

# Ruby development
alias r='rake'
alias be='bundle exec'
for gem in cap rspec spec cucumber spork; do
  alias $gem="bundle-exec $gem"
done

# Ruby on Rails
alias sc='script/console'
alias sg='script/generate'
alias sdb='script/dbconsole'
alias ss='script/server'

alias rt='RAILS_ENV=test rake'
alias migrate='r db:migrate db:test:prepare'
alias rmigrate='r db:migrate:redo db:test:prepare'

command_exists thin && alias ss='thin start'

#== Inline aliases ==#

# cd by .. or ... or ... or mv file ..../.
alias '..'='cd ..'
alias -g '...'='../..'
alias -g '....'='../../..'
alias -g '.....'='../../../..'

alias -g '..2'='../..'
alias -g '..3'='../../..'
alias -g '..4'='../../../..'
alias -g '..5'='../../../../..'

alias -g E='| `echo $EDITOR`' # Lazy evaluation so we're not locking this alias the the $EDITOR defined during the initialization
alias -g G='| grep'
alias -g S='| sed'
alias -g A='| awk'
alias -g L='| less'
alias -g C='| column'
alias -g T='| tail'
alias -g H='| head'
alias -g LL="2>&1 | less"

alias -g HL="--help"
alias -g NE="2> /dev/null"
alias -g NUL="> /dev/null 2>&1"

# Newest File and Newest Directory
# Example of use:
#    dmesg > log
#    mkdir status
#    cp NF ND
#
alias -g ND='$(ls -d *(/om[1]))' # newest directory
alias -g NF='$(ls *(.om[1]))'    # newest file

# Resume screen, use UTF-8
alias -g SC='screen -R -U'
