#!/usr/bin/env zsh
# Named directories and helper functions

# namedir name [path]
namedir () {
  local target
  if [[ $2 == "" ]]; then
    target=$(pwd)
  else
    target=$2
  fi

  hash -d $1=$target
}

local oldfile=~/.zsh-named-directories
local newfile=~/.zsh/named-directories

if [ -f $oldfile ]; then
  echo "Found deprecated $oldfile."
  if [ -f $newfile ]; then
    echo "Could not autofix since $newfile already exist. Diff:"
    diff -u $oldfile $newfile
    source $oldfile
  else
    echo "Autofixing"
    mv $oldfile $newfile
  fi
fi

if [ -f $newfile ]; then
  source $newfile
fi

# Give all projects a name
if [ -d ~/projects ]; then
  for dir in ~/projects/*(/); do
    namedir "$(basename $dir)" "$dir"
  done
fi

