#!/usr/bin/env zsh
# History

HISTSIZE=500
SAVEHIST=500
HISTFILE=~/.zsh/history

setopt append_history         # don't replace history when process exits
setopt hist_ignore_all_dups   # remove old dups when added again
setopt hist_verify            # verify ! expansions
