#!/usr/bin/env zsh
# Command replacements / aliases for commands with non-standard names

alias-if-exist () {
  if which $1 >/dev/null 2>/dev/null; then
    alias $2=$1
  fi
}

# Stupid Debian
alias-if-exist ack-grep ack

# Colordiff
alias-if-exist colordiff diff
