#!/usr/bin/env zsh
# Git settings and shortcuts

git_log_format='--pretty=format:%Cblue%h%Creset %cr %C(bold black)%an%Cgreen%d%Creset %s'

alias checkout='git checkout'
alias gadd='git add'
alias gco='git commit -v'
alias gpu='git push'
alias gri='git rebase -i'
alias gro='git rebase @{upstream}'
alias gmo='git merge @{upstream}'
alias gmm='git merge master'
alias gmm='git rebase master'
alias gup='git fetch'

alias gl="git log --graph '$git_log_format'"
alias s="git status --short"
alias gb="git branch -av"
alias master="git checkout master"
alias gd="git diff"
alias gdw="git diff --color-word"

# Deprecated
alias gst='echo use s'
alias gdf='echo use gd / gdw'
