#!/usr/bin/env zsh
# Ruby development with spork

drbon () {
  if [ -e .rspec ]; then
    echo ".rspec file already exist!"
    false
  else
    echo -n "--color\n--drb\n--format nested\n" > .rspec
  fi
}

drboff () {
  if [ -f .rspec ]; then
    grep -qe '--drb' .rspec
    if [[ $? == 0 ]]; then
      rm .rspec
    else
      echo "Wait a minute... The .rspec file does not have --drb in it. Maybe you didn't intend to delete it?"
      false
    fi
  fi
}
