#!/usr/bin/env zsh
# Ruby development with Bundler

alias be='bundle exec'

bundle-exec () {
  if [ -f Gemfile ]; then
    echo "(→ bundle exec $*)"
    bundle exec $@
  else
    $@
  fi
}

for gem in cap cucumber guard rspec spork; do
  alias $gem="bundle-exec $gem"
done

