#!/bin/zsh

# Based on code taken from
# http://weblog.rubyonrails.org/2006/3/9/fast-rake-task-completion-for-zsh
_rake_does_task_list_need_generating () {
  local stat_command formatting
  if [[ $IS_MAC == '1' ]]; then
    # Full path to use stock stat if gnuutils is installed
    stat_command="/usr/bin/stat"
    formatting="-f%m"
  else
    stat_command="stat"
    formatting="-c %Y"
  fi
  
  if [ ! -f .rake_tasks ]; then return 0;
  else
    accurate=$($stat_command $formatting .rake_tasks)
    changed=$($stat_command $formatting Rakefile)
    return $(expr $accurate '>=' $changed)
  fi
}

_rake () {
  if [ -f Rakefile ]; then
    if _rake_does_task_list_need_generating; then
      echo "\nGenerating .rake_tasks..." > /dev/stderr
      rake --silent --tasks | cut -d " " -f 2 > .rake_tasks
    fi
    compadd `cat .rake_tasks`
  fi
}

compdef _rake rake
