#!/usr/bin/env zsh
# Color shortcuts and magic

autoload colors
colors

function is256color() {
  if [[ $TERM == *256* ]]; then
    return true
  else
    return false
  fi
}

function colortest() {
  for code in {000..255}; do print -P -- "%F{$code}$code%f"; done | column -x -s ' '
}
