#!/bin/zsh
# Prompt settings and configuration

# From the manpage:
# If  the  PROMPT_SUBST option is set, the prompt string is first subjected to
# parameter expansion, command substitution and arithmetic expansion.
# See zshexpn(1).
set prompt_subst

# Capability to show SCM info in the prompt
autoload -Uz vcs_info

function {
  # Color user differently if we have a privileged user ("!")
  # %(nx.true.false)
  if is256color; then
    local time_color="%F{242}"
    local sec_color="%F{236}"
  else
    local time_color="$fg_bold[white]"
    local sec_color="$fg[white]"
  fi

  local user="%(!.$fg[red].$fg[green])%n"
  local current_time="$time_color%D{%H:%M}$sec_color%D{:%S}"
  local dir="$fg_bold[blue]%4~"
  local last_status="%(?.. $fg[blue]*%?)"
  local current_jobs="%(1j.$fg_bold[magenta]J%j .)"
  PROMPT="$user $current_time$last_status $dir $current_jobs$reset_color› "
}
