#!/usr/bin/env zsh
# If RVM is installed, source the config as the last thing we do
if [[ -s "$HOME/.rvm/scripts/rvm" ]]; then
  source "$HOME/.rvm/scripts/rvm"

  function rvm-ruby-version () {
    echo $rvm_ruby_string | cut -d '-' -f 2
  }
else
  function rvm-ruby-version () {
  }
fi
