#!/bin/zsh

# Make everything dark gray
echo -en $fg_bold[black]

#
# Echoes a short fortune
#

if [[ $(which fortune &> /dev/null; echo $?) == "0" ]]; then
  echo
  fortune -as
  echo
fi

#
# Show the uptime, too
#
echo -n Uptime:
uptime
echo

# Restore the color
echo -en $fg[default]

# Warn for missing important directories
if [ ! -d ~/.zsh ]; then
  echo "Warning: ~/.zsh directory not present. Please mkdir it for caching and history to work properly"
fi
