#!/usr/bin/env zsh
# If RVM is installed, source the config as the last thing we do
if [[ -s "$HOME/.rvm/scripts/rvm" ]]; then
  function rvm-ruby-version () {
    rvm-prompt v g s
  }

  source "$HOME/.rvm/scripts/rvm"
fi
