#!/usr/bin/env zsh
# If RVM is installed, source the config as the last thing we do
if [[ -s /usr/local/rvm/scripts/rvm ]]; then
  source /usr/local/rvm/scripts/rvm
fi

if [[ -s "$HOME/.rvm/scripts/rvm" ]]; then
  source "$HOME/.rvm/scripts/rvm"
fi

if which rvm-prompt >/dev/null 2>/dev/null; then
  function rvm-ruby-version () {
    rvm-prompt v g s
  }
fi

