# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-playbook.json
- name: Set up local environment
  hosts: localhost
  become: false
  become_user: root
  become_method: sudo

  vars:
    user_home: "{{ lookup('env', 'HOME') or '/home/mange' }}"
    xdg_config_home: "{{ lookup('env', 'XDG_CONFIG_HOME') or (lookup('env', 'HOME') or '/home/mange') + '/.config' }}"
    xdg_data_home: "{{ lookup('env', 'XDG_DATA_HOME') or (lookup('env', 'HOME') or '/home/mange') + '/.local/share' }}"
    xdg_bin: "{{ (lookup('env', 'HOME') or '/home/mange') + '/.local/bin' }}"
    xdg_cache_home: "{{ lookup('env', 'XDG_DATA_HOME') or (lookup('env', 'HOME') or '/home/mange') + '/.cache' }}"
    inside_docker: "{{ lookup('env', 'INSIDE_DOCKER') == '1' }}"

  # Set some XDG stuff that is likely to be used during installation of
  # packages in this setup.
  environment:
    XDG_CONFIG_HOME: "{{ xdg_config_home }}"
    XDG_DATA_HOME: "{{ xdg_data_home }}"
    XDG_CACHE_HOME: "{{ xdg_cache_home }}"
    GNUPGHOME: "{{ xdg_data_home }}/gnupg"
    NPM_CONFIG_USERCONFIG: "{{ xdg_config_home }}/npm/config"
    NPM_CONFIG_CACHE: "{{ xdg_cache_home }}/npm"
    CARGO_HOME: "{{ xdg_data_home }}/cargo"
    RUSTUP_HOME: "{{ xdg_data_home }}/rustup"

  roles:
    - { role: group-base, tags: [base] }
    - { role: dotfiles, tags: [dotfiles] }
    - { role: gpg-config, tags: [gpg] }

    - { role: host-socia, tags: [system], when: 'ansible_hostname == "socia"' }
    - {
        role: host-krista,
        tags: [system],
        when: 'ansible_hostname == "krista"',
      }
    - { role: host-knas, tags: [system], when: 'ansible_hostname == "knas"' }
