#!/bin/zsh
# This file contains named directories for you to use.
# Just place one on each line, following this syntax:
#    namedir $name $path
# For example:
#    namedir favs /home/joe/bookmarks
#    namedir shared /usr/local/shared_files/
# You can then use them like this:
#   % mv song.mp3 ~shared
#   % cd ~shared
#   % mv song2.mp3 ~shared/music/unknown
#   % rm -rf ~favs

namedir dot $HOME/dotfiles

