# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json
- tags: group-gui
  block:
    - name: Install GUI packages
      when: ansible_os_family == "Archlinux"
      kewlfft.aur.aur:
        state: present
        name:
          # Graphical environment
          - xorg
          - adapta-gtk-theme # gtk theme
          - x11-ssh-askpass
          - xdg-desktop-portal-gtk
          # GUI tools
          - autorandr # xrandr config for screen combinations
          - feh # image viewer and background setter
          - flameshot # Screenshot app
          - gucharmap # character lookup gui, good for icon fonts
          - lxappearance # dunno lol
          - lxrandr # gui for xrandr
          - mugshot # Customize user avatar
          - mugshot # Customize user avatar (used in my AwesomeWM theme)
          - network-manager-applet
          - parcellite # Clipboard manager
          - rofi # graphical selector and app launcher
          - rofi-emoji
          - udiskie # auto-mounter for devices (and tray icon)
          - workrave # anti-rsi + workbreak timer
          - xcape # Make Super into both Super and Escape
          - xsel # used by a lot of cli tools to copy/paste
          - zenity # GUI prompts from scripts (ytpip, etc.)
          # Browser
          - brave-beta-bin
          - firefox-developer-edition
          # File management
          - spacefm
          # Media
          - mpv
          - pavucontrol # Pulseaudio settings gui
          - playerctl
          - pipewire
          # - pulseaudio # Audio server
          - pulsemixer # Pulseaudio TUI mixer
          - spotify # A proprietary music streaming service
          - vlc
          # PDF, comics, etc.
          - zathura
          - zathura-cb # Adds comic book support to zathura
          - zathura-djvu # DjVu support for Zathura
          - zathura-pdf-mupdf # EPUB, PDF and XPS support based on MuPDF
          # Chatting
          - telegram-desktop # chat
          - discord # All-in-one voice and text chat for gamers that's free and secure.
          # Password manager, encryption, etc.
          - bitwarden-cli # CLI for password manager
          - bitwarden-rofi # Bitwarden in Rofi
          - keybase
          - keybase-gui
          # Yubikey
          - yubikey-manager
          - yubikey-manager-qt
          - ccid # smartcard drivers + pcscd
          # Syncthing
          - syncthing
          # Spell checking
          - hunspell
          - hunspell-en_US
          - hunspell-sv
          - aspell
          - aspell-en
          - aspell-sv
          - ispell
          # Torrents and similar
          - transmission-remote-gtk
          - transmission-cli
          # Misc
          - xdg-utils # Desktop software support
          - gnome-keyring # To get GPG etc. unlocked globally

    - name: Install GUI packages (git)
      when: ansible_os_family == "Archlinux"

      # These packages have a bigger tendency than normal of failing, and there
      # probably won't be a lot of stuff in this whole setup that would *break* if a
      # package here is missing. Let's keep going if some of them fails to install.
      ignore_errors: true

      kewlfft.aur.aur:
        state: present
        name:
          # Graphical environment
          - picom-animations-git # Fork of picom with animations
          # Terminal
          - wezterm-git

    - name: Ensure rsync is installed
      become: true
      package:
        name: rsync
        state: present

    - name: Ensure wallpapers directory exist
      become: true
      file:
        path: "/usr/share/wallpapers/Mange"
        state: directory
        owner: root
        group: root
        mode: u=rwX,g=rX,o=rX

    - name: Copy wallpapers to system directory
      become: true
      # NOTE: Requires rsync to be installed
      ansible.posix.synchronize:
        src: "data/wallpapers/"
        dest: "/usr/share/wallpapers/Mange"
        archive: true
        delete: true

    - name: Set permissions of system wallpapers
      become: true
      file:
        path: "/usr/share/wallpapers/Mange"
        state: directory
        recurse: true
        owner: root
        group: root
        mode: u=rwX,g=rX,o=rX

    - name: Install udiskie polkit config
      become: true
      copy:
        src: polkit/50-udiskie.rules
        dest: /etc/polkit-1/rules.d/50-udiskie.rules
        group: root
        owner: root
        mode: u=rw,g=r,o=r

    - name: "Enable services"
      become: true
      when: not inside_docker
      systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - pcscd # smartcard daemon, for Yubikey, etc.

    - name: "Enable user services"
      when: not inside_docker
      systemd:
        scope: user
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - syncthing

    - name: Setup default apps
      shell: |
        xdg-mime default spacefm.desktop inode/directory
