# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json
- tags: group-base
  block:
    - name: Configure pacman
      become: true
      lineinfile:
        path: /etc/pacman.conf
        line: "{{ item.line }}"
        regexp: "{{ item.regexp }}"
        backrefs: "{{ item.backrefs }}"
      loop:
        - { line: "Color", regexp: "#Color", backrefs: false }
        - { line: "CheckSpace", regexp: "#CheckSpace", backrefs: false }
        - {
            # line: "IgnorePkg = kglobalaccel",
            line: "# IgnorePkg = kglobalaccel",
            regexp: "IgnorePkg",
            backrefs: false,
          }

    - name: Enable Multilib
      become: true
      ini_file:
        path: /etc/pacman.conf
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value | default(omit) }}"
      loop:
        - {
            section: "multilib",
            option: "Include",
            value: "/etc/pacman.d/mirrorlist",
          }

    - name: Update pacman
      become: true
      pacman:
        update_cache: true
        upgrade: false

    - name: Install base-devel
      become: true
      pacman:
        name: base-devel
        state: present

    - name: Upgrade pacman
      tags: install-updates
      become: true
      pacman:
        update_cache: false
        upgrade: true

    - include_role:
        name: paru

    - name: Install arch systemd units
      become: true
      copy:
        src: systemd/arch/
        dest: /etc/systemd/system/
        group: root
        owner: root
        mode: u=rw,g=r,o=r
      register: arch_systemd_units

    - name: Reload systemd
      become: true
      when: arch_systemd_units.changed and not inside_docker
      systemd:
        daemon_reload: true

    - name: Enable timesyncd service
      become: true
      when: not inside_docker
      systemd:
        name: systemd-timesyncd
        enabled: true
        state: started

    - name: "Enable download-pacman-updates timer"
      become: true
      when: not inside_docker
      systemd:
        name: download-pacman-updates.timer
        enabled: true
        state: started
