# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json
- block:
    - name: Enable package repos
      become: true
      package:
        name: epel-release
        state: present

    - name: Add Docker repository
      become: true
      yum_repository:
        name: docker-ce-stable
        description: "Docker CE Stable - $basearch"
        baseurl: "https://download.docker.com/linux/centos/7/$basearch/stable"
        gpgcheck: true
        gpgkey: https://download.docker.com/linux/centos/gpg
        enabled: true

    - name: Add Tailscale repository
      become: true
      yum_repository:
        name: tailscale-stable
        description: "Tailscale stable"
        baseurl: "https://pkgs.tailscale.com/stable/centos/7/$basearch"
        gpgcheck: false
        repo_gpgcheck: true
        gpgkey: https://pkgs.tailscale.com/stable/centos/7/repo.gpg
        enabled: true

    - name: Add Ghettoforge repository
      become: true
      yum:
        name: "http://mirror.ghettoforge.org/distributions/gf/gf-release-latest.gf.el{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
        disable_gpg_check: yes

    - name: Enable/Disable ghettoforge repos
      become: true
      ini_file:
        dest: /etc/yum.repos.d/gf.repo
        section: "{{ item.name }}"
        option: enabled
        value: "{{ 1 if item.enable else 0 }}"
        no_extra_spaces: yes
      with_items:
        - { name: "gf", enable: true }
        - { name: "gf-plus", enable: true }
        - { name: "gf-testing", enable: false }
        - { name: "gf-source", enable: false }
        - { name: "gf-plus-source", enable: false }
        - { name: "gf-testing-source", enable: false }

    - name: Add EndPoint repository
      become: true
      yum:
        name: "https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm"
        state: present
