#!/usr/bin/env bash
set -e

# shellcheck source=../../../data/gruvbox/colors.env
source "${XDG_DATA_HOME}/gruvbox/colors.env"

task_cmd="task rc.echo.command=no rc._forcecolor=no rc.blanklines=false rc.hooks=off rc.verbose=nothing"

next_task_id=$($task_cmd limit:1 next | head -n1 | awk '{ print $1 }')

if [[ -n $next_task_id ]]; then
  project=$($task_cmd _get "${next_task_id}.project")
  description=$($task_cmd _get "${next_task_id}.description")
  due=$($task_cmd _get "${next_task_id}.due" | date-to-relative || true)

  is_active=$($task_cmd _get "${next_task_id}.tags.ACTIVE" || true)
  is_due_today=$($task_cmd _get "${next_task_id}.tags.DUETODAY" || true)
  is_overdue=$($task_cmd _get "${next_task_id}.tags.OVERDUE" || true)

  if [[ -n $is_overdue ]]; then
    color="%{F${bright_red}}"
  elif [[ -n $is_due_today ]]; then
    color="%{F${bright_aqua}}"
  elif [[ -n $is_active ]]; then
    color="%{F${bright_yellow}}"
  else
    color=""
  fi

  if [[ -n $project ]]; then
    echo -n "[${project}] "
  fi

  if [[ -n $due ]]; then
    echo -n "(${due}) "
  fi

  echo "${color}#${next_task_id} ${description}"
else
  echo "[No task]"
fi
