#!/usr/bin/env bash
set -e

root="$(dirname "$0")"

task_cmd="task rc.echo.command=no rc._forcecolor=no rc.blanklines=false rc.hooks=off rc.verbose=nothing"

# shellcheck source=../../../data/gruvbox/colors.env
source "${root}/../../../data/gruvbox/colors.env"

ready=$($task_cmd +READY count)
overdue=$($task_cmd +OVERDUE count)
today=$($task_cmd +TODAY count)
week=$($task_cmd +WEEK count)

echo -n " ${today}/${week}/${ready}"

if [[ $overdue -gt 0 ]]; then
  echo -n " "
	echo -n "%{F${bright_red}} ${overdue}%{F-}"
fi
