# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json
- block:
    - name: Install Neovim (git)
      become: false
      kewlfft.aur.aur:
        name:
          - neovim-git

          # Plugin hosts
          - python # For neovim plugins
          - python-pip # To install neovim package for Python
          - nodejs # For neovim plugins
          - yarn # For neovim plugins
          - npm # To install neovim package for nodejs

          # Language servers, linters, etc.
          - texlab # LaTeX
          - lua-language-server
          - prettier # TS, JS, CSS, etc.
          - rust-analyzer
          - shfmt
          - shellcheck
          - stylua-bin
          - yaml-language-server
          - bash-language-server
          - bash-completion # dependency of bash-language-server

    - name: Install Neovim NodeJS plugin
      shell: |
        npm install -g --no-audit --no-fund \
          neovim

    - name: Install Neovim Python plugin
      become: false
      shell: |
        pip install --user --upgrade --upgrade-strategy eager -q neovim

    - name: Install Neovim Ruby plugin
      become: false
      shell: |
        script_candidates=(
          "${XDG_CONFIG_HOME}/shells/enable-rvm"
          "${HOME}/Projects/dotfiles/config/shells/enable-rvm"
          ../config/shells/enable-rvm
          /usr/share/rvm/scripts/rvm
          /usr/local/rvm/scripts/rvm
          "${HOME}/.rvm/scripts/rvm"
        )

        for candidate in "${script_candidates[@]}"; do
          if [ -f "$candidate" ]; then
            # shellcheck source=/dev/null
            source "$candidate"
            break
          fi
        done

        if type rvm >/dev/null 2>/dev/null; then
          rvm @global do gem install neovim
          rvm all do gem install neovim
        elif hash gem >/dev/null 2>/dev/null; then
          gem install -q neovim
        fi

    - name: Install language servers through NPM
      shell: |
        npm install -g --no-audit --no-fund \
          dockerfile-language-server-nodejs \
          @tailwindcss/language-server \
          typescript-language-server \
          vscode-langservers-extracted
