#!/usr/bin/env bash
# Shebang is here for vim syntax coloring; it would be useless to execute it.

# It is important that this works in both bash and zsh, but other shells need
# not apply.
if [[ -n $BASH_VERSION || -n $ZSH_VERSION ]]; then
  if [[ $_mange_customized_paths != "yes" ]]; then
    _mange_customized_paths="yes"

    if [[ -n "$BASH_VERSION" ]]; then
      # Bash does not automatically have a $path array like ZSH; create it
      # manualy by splitting existing PATH variable.
      IFS=: read -r -a path <<< "$PATH"
    fi

    path=(
      "$HOME/.local/bin"

      .git/safe/../../bin

      "$HOME/.cargo/bin"
      "$HOME/.rvm/bin"
      "$XDG_DATA_HOME/npm/packages/bin"

      "$HOME/.yarn/bin"

      "${path[@]}"
    )

    # Also set up custom MANPATH
    MANPATH="${XDG_DATA_HOME}/npm/packages/share/man:$(manpath --quiet)"
    export MANPATH

    if [[ -n "$ZSH_VERSION" ]]; then
      # zsh has a way easier time exporting arrays to the path...
      # -U (unique) removes any duplicated entries
      export -U path
    else
      # Bash cannot filter out duplicated entries in an easy way like that... :(
      PATH="$(IFS=:; echo "${path[*]}")"
      export PATH
      # Remove this temporary variable
      unset path
    fi
  fi
fi
