#!/usr/bin/bash

# Make sure keyboard is set up correctly. Replugging a keyboard resets Xmodmap,
# and this is common as I unplug my keyboard from my laptop before it goes to
# sleep.
fix-keyboard

# Reflow screens
# autorandr --change

# Show reminder, if it was more than 1 hour since last locked
last_lock_file="$XDG_RUNTIME_DIR/locking-monitor-time-of-last-lock"
if [[ -f "$last_lock_file" ]]; then
  time_of_last_lock=$(cat "$last_lock_file")
  one_hour_ago=$(date -d "1 hour ago" +%s)
  if [[ "$time_of_last_lock" -lt "$one_hour_ago" ]]; then

    startup-reminder

  fi
fi
