return {
  {
    "simrat39/symbols-outline.nvim",
    opts = {
      lsp_blacklist = {},
      symbol_blacklist = {
        -- 'File',
        -- 'Module',
        -- 'Namespace',
        -- 'Package',
        -- 'Class',
        -- 'Method',
        -- 'Property',
        -- 'Field',
        -- 'Constructor',
        -- 'Enum',
        -- 'Interface',
        -- 'Function',
        -- 'Variable',
        -- 'Constant',
        "String",
        "Number",
        "Boolean",
        "Array",
        "Object",
        "Key",
        "Null",
        "EnumMember",
        "Struct",
        "Event",
        "Operator",
        "TypeParameter",
      },
      winblend = 20,
    },
  },
}
