# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json
- block:
    - name: Install GUI programs
      become: false
      kewlfft.aur.aur:
        name:
          # Graphical environment
          - lightdm
          - lightdm-gtk-greeter
          - lightdm-gtk-greeter-settings
          - xorg
          - adapta-gtk-theme # gtk theme
          - picom-ibhagwan-git # Fork of picom with better blurring and rounded corners
          # GUI tools
          - autorandr # xrandr config for screen combinations
          - feh # image viewer and background setter
          - flameshot # Screenshot app
          - gucharmap # character lookup gui, good for icon fonts
          - lxappearance # dunno lol
          - lxrandr # gui for xrandr
          - mugshot # Customize user avatar
          - mugshot # Customize user avatar (used in my AwesomeWM theme)
          - network-manager-applet
          - parcellite # Clipboard manager
          - pavucontrol # pulse audio settings gui
          - rofi # graphical selector and app launcher
          - rofi-emoji
          - udiskie # auto-mounter for devices (and tray icon)
          - workrave # anti-rsi + workbreak timer
          - xcape # Make Super into both Super and Escape
          - xsel # used by a lot of cli tools to copy/paste
          - zenity # GUI prompts from scripts (ytpip, etc.)
          # Terminal
          - wezterm-git
          # Browser
          - brave-beta-bin
          - firefox-developer-edition
          # File management
          - spacefm
          # Media
          - pulseaudio # Audio server
          - spotify # A proprietary music streaming service
          - playerctl
          - vlc
          - mpv
          # PDF, comics, etc.
          - zathura
          - zathura-cb # Adds comic book support to zathura
          - zathura-djvu # DjVu support for Zathura
          - zathura-pdf-mupdf # EPUB, PDF and XPS support based on MuPDF
          # Chatting
          - telegram-desktop # chat
          - discord # All-in-one voice and text chat for gamers that's free and secure.
          # Password manager, encryption, etc.
          - bitwarden-cli # CLI for password manager
          - bitwarden-rofi # Bitwarden in Rofi
          - keybase
          - keybase-gui
          # Yubikey
          - yubikey-manager
          - yubikey-manager-qt
          - ccid # smartcard drivers + pcscd
          # Syncthing
          - syncthing
          - syncthing-gtk-python3
          # Spell checking
          - hunspell
          - hunspell-en_US
          - hunspell-sv
          - aspell
          - aspell-en
          - aspell-sv
          - ispell
          # Misc
          - xdg-utils # Desktop software support
          - gnome-keyring # To get GPG etc. unlocked globally
      when: ansible_os_family == "Archlinux"
