# shellcheck shell=bash
# shellcheck source=/dev/null
source "${XDG_CONFIG_HOME:-${HOME}/.config}/shells/common"

[ -f /usr/share/fzf/completion.bash ] && source /usr/share/fzf/completion.bash
[ -f /usr/share/fzf/key-bindings.bash ] && source /usr/share/fzf/key-bindings.bash
