#!/bin/sh

# Run default xinit stuff as given by the OS
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    # shellcheck source=/dev/null
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# shellcheck source=/dev/null
[ -f /etc/xprofile ] && . /etc/xprofile

# shellcheck source=/home/mange/.config/xsession/profile
. "${XDG_CONFIG_HOME:-${HOME}/.config}/xsession/profile"

# Start my WM
export DESKTOP_SESSION=awesome
exec awesome
