# bootstrap zsh so it will read all other startup files from the XDG config
# directory, then load the real zshenv file.
source "${XDG_CONFIG_HOME:-${HOME}/.config}/zsh/xdg_zealotry"
source "${XDG_CONFIG_HOME}/zsh/zshenv"
