# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json
- block:
    - include_tasks: arch.yml
      when: ansible_os_family == "Archlinux"
      tags:
        - arch
