#!/usr/bin/env zsh

run-changed-specs() {
  local command="${1:-rspec}"
  # List changes to spec files, ignoring deleted files and print last column.
  # Last column should be the existing filename. If (M)odified, it'll just be
  # two columns, but if renamed, git status will output "old -> new".
  local changed="$(git status --porcelain | grep '_spec\.rb' | grep -vE '\bD\b' | awk '{ print $NF }')"
  if [[ -n $changed ]]; then
    echo $changed | xargs $command
  else
    echo "No changed spec files could be found." > /dev/stderr
  fi
}
