#!/usr/bin/env zsh

run-changed-specs() {
  local command
  if [[ -f bin/rspec ]]; then
    command="bin/rspec"
  else
    command="rspec"
  fi
  # List changes to spec files, ignoring deleted files and print last column.
  # Last column should be the existing filename. If (M)odified, it'll just be
  # two columns, but if renamed, git status will output "old -> new".
  local changed="$(git status --porcelain | grep '_spec\.rb' | grep -vE '\bD\b' | awk '{ print $NF }')"
  if [[ -n $changed ]]; then
    xargs --arg-file=<(echo $changed) $command $@
  else
    echo "No changed spec files could be found." > /dev/stderr
  fi
}
