# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json
- block:
    - name: Add mange to video and input groups
      become: true
      user:
        name: mange
        groups:
          - video # Control brightness
          - input # Control LEDs
        append: true

    - name: Install workstation packages
      when: ansible_os_family == "Archlinux"
      kewlfft.aur.aur:
        state: present
        name:
          # Hardware
          - bluez # Bluetooth
          - bluez-utils # Bluetooth
          - blueman

          # Files and directories
          - fzf
          - tree
          - vimv # Batch-rename files using Vim
          - fd # Simple, fast and user-friendly alternative to find

          # Docs and references
          - tldr

          # Network
          - networkmanager
          - httpie
          - nmap
          - rsync
          - curl

          # Modern UNIX replacements
          - bat
          - exa
          - htop
          - prettyping
          - procs # Modern replacement for ps(1)
          - ripgrep
          - fd # Simple, fast and user-friendly alternative to find

          # Git and VCS
          - git
          - github-cli
          - git-delta # Better diff tool for Git
          - hub

          # Task and note keeping
          - task # Taskwarrior
          - vit # Taskwarrior TUI
          # A powerful knowledge base that works on top of a local folder of
          # plain text Markdown files. WARNING: Not Free Software or Open
          # Source.
          - obsidian

          # Calculator
          - libqalculate
          - gnuplot # For plotting support

          # Archives
          - atool
          - p7zip
          - unrar
          - unzip
          - xz
          - zip

          # Misc developer tooling
          - postgresql
          - postgresql-libs
          - jiq # interactive jq
          - jq
          - watchexec
          - gron-bin # transforms JSON into discrete assignments to make it easier to grep.
          - parallel
          - pastel

          # CLI toys
          - dotacat # like lolcat
          - figlet
          - figlet-fonts
          - figlet-fonts-extra

          # Media
          - mediainfo
          - youtube-dl
          - imagemagick # for image previews, post-processing, etc.
          - ghostscript # imagemagick optional dependency for PDF support

          # Misc
          - duplicity # Backup tool
          - tydra

    - name: Install workstation PIP packages
      become: true
      pip:
        state: latest
        name:
          - pgcli
          # TODO: Cannot install http-prompt since it is incompatible with
          # pgcli; they depend on the same thing but in different versions and pip cannot
          # deal with that…

    - name: Install blueman polkit config
      become: true
      copy:
        src: polkit/50-blueman.rules
        dest: /etc/polkit-1/rules.d/50-blueman.rules
        group: root
        owner: root
        mode: u=rw,g=r,o=r

    - name: Install systemd units
      become: true
      copy:
        src: systemd/
        dest: /etc/systemd/system/
        group: root
        owner: root
        mode: u=rw,g=r,o=r
      register: systemd_units

    - name: Reload systemd
      become: true
      when: not inside_docker
      systemd:
        daemon_reload: true

    - name: "Enable services"
      become: true
      when: not inside_docker
      systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - NetworkManager
        - duplicity-backup.timer
        - bluetooth
