# A note about the shortcut colors:
#   - Green = Will return to tydra after
#   - Red = Will exit tydra
#   - Blue = Opens another tydra menu
#   - Yellow and Cyan are special colors for certain menus.
#
global:
  layout: columns
  shortcut_color: green
pages:
  root:
    title: Welcome
    groups:
      - title: TODO / Calendars
        entries:
          - shortcut: a
            title: Add task
            return: true
            mode: wait
            command: |
              clear
              echo -n "Add: "
              read -r input
              if [ -n "$input" ]; then
                task add $input
              else
                echo "Aborted"
              fi

          - shortcut: r
            title: Edit reminder
            mode: exec
            shortcut_color: red
            command: nvim ~/Reminder

          - shortcut: o
            title: Edit local overrides
            mode: exec
            shortcut_color: red
            command: |
              nvim "$XDG_CONFIG_HOME/taskwarrior/local-overrides"

      - title: Shortcuts
        entries:
          - shortcut: D
            title: Downloads (GUI)
            shortcut_color: red
            return: false
            command: spacefm ~/Downloads
            mode: background

      - title: System
        entries:
          - shortcut: p
            title: Power menu
            return: power
            shortcut_color: blue

          - shortcut: f
            title: Filesystem menu
            return: fs
            shortcut_color: blue

          - shortcut: u
            title: Audio mixer (TUI)
            return: false
            mode: exec
            shortcut_color: red
            command: pulsemixer

          - shortcut: U
            title: Audio settings (GUI)
            return: false
            mode: background
            shortcut_color: red
            command: pavucontrol

          - shortcut: b
            title: Bluetooth device selector
            return: false
            mode: background
            shortcut_color: red
            command: bt-select

          - shortcut: B
            title: Bluetooth settings
            return: false
            mode: background
            shortcut_color: red
            command: blueman-manager

          # TODO: Command to toggle default audio sink (requires being able to
          # show current sink)

          - shortcut: w
            title: Wifi menu
            mode: exec
            shortcut_color: red
            command: nmtui connect

      - entries:
          - shortcut: q
            title: Quit
            shortcut_color: red
            return: false

  fs:
    title: Filesystem
    settings:
      layout: list
    groups:
      - entries:
          - shortcut: u
            title: "Unmount media (select)"
            return: true
            command: rofi-unmount

          - shortcut: U
            title: "Unmount media (all)"
            return: false
            shortcut_color: red
            command: udiskie-umount --all

          - shortcut: q
            title: Go back
            shortcut_color: blue
            return: root

  power:
    title: Power settings
    settings:
      layout: list
      shortcut_color: red
    groups:
      - entries:
          - shortcut: s
            title: Suspend
            mode: exec
            command: "udiskie-umount --all && systemctl suspend-then-hibernate"

          - shortcut: h
            title: Hibernate
            mode: exec
            command: "udiskie-umount --all && systemctl hibernate"

          - shortcut: l
            title: Log out
            mode: exec
            command: wmquit --force

          - shortcut: q
            title: Go back
            shortcut_color: blue
            return: root
