# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json
- block:
    - name: Configure pacman
      lineinfile:
        path: /etc/pacman.conf
        line: "{{ item.line }}"
        regexp: "{{ item.regexp }}"
        backrefs: "{{ item.backrefs }}"
      loop:
        - { line: "Color", regexp: "#Color", backrefs: false }
        - { line: "CheckSpace", regexp: "#CheckSpace", backrefs: false }
        - {
            line: "IgnorePkg = kglobalaccel",
            regexp: "IgnorePkg",
            backrefs: false,
          }

    - name: Enable Multilib
      ini_file:
        path: /etc/pacman.conf
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value | default(omit) }}"
      loop:
        - {
            section: "multilib",
            option: "Include",
            value: "/etc/pacman.d/mirrorlist",
          }

    - name: Update pacman
      pacman:
        update_cache: true
        upgrade: false

    - name: Install base-devel
      pacman:
        name: base-devel
        state: present

    - name: Upgrade pacman
      pacman:
        update_cache: false
        upgrade: true

    # Paru requires Rust to be installed; and I want to install it using
    # "rustup" rather than makepkg just installing "rust" as a dependency and
    # me then having to clean that up afterward.
    - include_tasks: tasks/rust.yml
    - include_tasks: tasks/paru.yml
