# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json
# Installing Paru is an interesting process in Ansible.
#
# Here's the basic outline of it:
#   1. If paru is not available, clone the repo to a global path.
#   2. If cloned repo exist, then install it using the aur module.
#   3. If cloned repo exist and the command exist, delete the cloned repo.
#   4. Tell aur helper to make sure paru is the latest installed version.
#      (Which makes paru manage itself)
- block:
    # Step 1
    - block:
        - name: Check if Paru is installed
          stat:
            path: /usr/bin/paru
          register: paru_bin

        - name: Clone paru repo
          when: not paru_bin.stat.exists
          shell: |
            set -e
            sudo mkdir -p /opt/paru
            sudo chown mange:mange /opt/paru
            [ ! -d /opt/paru/.git ] && git clone https://aur.archlinux.org/paru.git /opt/paru || true
          become_user: mange

    # Step 2
    - block:
        - name: Check if Paru repo is cloned
          stat:
            path: /opt/paru/.git
          register: paru_repo

        - name: Install paru through repo
          when: paru_repo.stat.exists
          become_user: mange
          kewlfft.aur.aur:
            name: paru
            state: present
            local_pkgbuild: /opt/paru
            use: makepkg

    # Step 3
    - block:
        - name: Check if Paru is installed
          stat:
            path: /usr/bin/paru
          register: paru_bin

        - name: Check if Paru repo is cloned
          stat:
            path: /opt/paru/.git
          register: paru_repo

        - name: Remove paru repo
          when: paru_bin.stat.exists and paru_repo.stat.exists
          command: rm -rf /opt/paru

    # Step 4
    - name: Make paru manage paru
      kewlfft.aur.aur:
        name: paru
        state: latest
        use: paru
