# vim: ft=zsh
function {
  if [[ $customized_paths != "yes" ]]; then
    customized_paths="yes"

    path=(
      /usr/local/sbin
      /usr/sbin
      /sbin

      $HOME/.local/bin
      $HOME/.local/share/umake/bin

      .git/safe/../../bin

      $HOME/.rvm/bin
      $HOME/.cargo/bin
      $HOME/.yarn/bin

      /opt/*/bin(/N)
      /snap/bin

      "$path[@]"
    )
    typeset -Ugx path # uniq global export
  fi
}

# Non-interactive shells should still get a hold of rvm
# Vim runs zsh with -c; a tty is present but it still isn't interactive
if [ ! -t ] || [[ $VIM != "" ]]; then
  if [[ -s /usr/local/rvm/scripts/rvm ]]; then
    source /usr/local/rvm/scripts/rvm
  elif [[ -s "$HOME/.rvm/scripts/rvm" ]]; then
    source "$HOME/.rvm/scripts/rvm"
  fi
fi

