#!/bin/zsh

# Run local stuff, too.
if [[ -f ~/.zshprofile.local ]]; then
  echo "$(tput setaf 1)\
Warning: You have a ~/.zshprofile.local file. \
Move it to ${XDG_CONFIG_HOME}/zsh/zshprofile.local!\
$(tput sgr0)" > /dev/stderr
  source ~/.zshprofile.local
fi

if [[ -f "${XDG_CONFIG_HOME}/zsh/zshprofile.local" ]]; then
  source "${XDG_CONFIG_HOME}/zsh/zshprofile.local"
fi
