#!/usr/bin/env zsh

run-branch-specs() {
  local command
  if [[ -f bin/rspec ]]; then
    command="bin/rspec"
  else
    command="rspec"
  fi
  # Filter out deleted files from the filenames using --diff-filter.
  #
  # Last column should be the existing filename. If (M)odified, it'll just be
  # two columns, but if (R)enamed, output is "R old new".
  local changed="$(git diff origin/master.. --name-status --diff-filter=d | grep '_spec\.rb' | awk '{ print $NF }')"
  if [[ -n $changed ]]; then
    xargs --arg-file=<(echo $changed) $command $@
  else
    echo "No changed spec files could be found." > /dev/stderr
  fi
}
