# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-playbook.json
- name: Set up local environment
  hosts: localhost
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: Load variables
      include_vars: variables.yml
      tags:
        - always

    - include_role:
        name: host-morbidus
      when: ansible_hostname == "morbidus"

    - include_role:
        name: host-krista
      when: ansible_hostname == "krista"
