# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json
- block:
    - when: ansible_os_family == "Archlinux"
      block:
        - name: Install docker (Arch)
          kewlfft.aur.aur:
            state: present
            name:
              - docker
              - docker-credential-secretservice
              - docker-compose

    - when: ansible_distribution == "CentOS"
      block:
        - name: Install docker (Centos)
          become: true
          package:
            state: present
            name:
              - docker

    - name: Ensure docker group
      become: true
      group:
        name: docker
        state: present

    - name: Add mange to docker group
      become: true
      user:
        name: mange
        groups: docker
        append: true

    - name: Enable docker service
      become: true
      when: not inside_docker
      systemd:
        name: docker
        enabled: true
        state: started
