# Catppuccin
[colors]
foreground = "#D9E0EE"
background = "#1E1E2E"
cursor_bg = "#F5E0DC"
cursor_border = "#F5E0DC"
cursor_fg = "#1E1E2E"
selection_bg = "#575268"
selection_fg = "#D9E0EE"

ansi = [ "#6E6C7E", "#F28FAD", "#ABE9B3", "#FAE3B0", "#96CDFB", "#F5C2E7","#89DCEB", "#C3BAC6", ]
brights = [ "#988BA2", "#F28FAD", "#ABE9B3", "#FAE3B0", "#96CDFB", "#F5C2E7", "#89DCEB", "#D9E0EE", ]
