# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json
- block:
    - name: Install fonts
      become: false
      when: ansible_os_family == "Archlinux"
      kewlfft.aur.aur:
        name:
          - font-victor-mono
          - gnu-free-fonts # FreeMono; monospaced Unicode font. Popular in Kaomoji, etc.
          - noto-fonts # Android
          - noto-fonts-emoji # Emoji
          - noto-fonts-extra # etc.
          - otf-fira-mono
          - ttf-ancient-fonts # Just because it is cool
          - ttf-dejavu
          - ttf-droid # Android
          - ttf-fira-code
          - ttf-fira-mono
          - ttf-fira-sans
          - ttf-hack
          - ttf-inconsolata
          - ttf-liberation # Arial, Times New Roman, etc.
          - ttf-monaco
          - ttf-nerd-fonts-symbols
          - ttf-roboto # Android
          # Eastern fonts, for Kaomoji, when opening Japanese websites, etc.
          - otf-ipafont # Japanese
          - ttf-arphic-uming # Chinese
          - ttf-baekmuk # Korean
          - ttf-indic-otf # Indic; includes ಠ_ಠ
      register: font_install

    - name: Make sure fontconfig directory exists
      become: false
      file:
        path: "{{ xdg_config_home }}/fontconfig/conf.d"
        state: directory

    - name: Install fontconfig fallback
      become: false
      file:
        src: 90-fallbacks.conf
        dest: "{{ xdg_config_home }}/fontconfig/conf.d/90-fallbacks.conf"
        state: link
        force: true
        follow: false
      register: font_fallbacks

    - name: Rebuild font cache
      when: font_install.changed or font_fallbacks.changed
      command: fc-cache
