#!/usr/bin/env bash
set -e

time=

if [[ $# -gt 0 ]]; then
  time=("$1" "$2")
else
  time=($(date +"%I %M"))
fi

hour="${time[0]}"
minute="${time[1]#0}"

# NOTE: date's %I starts on 1, not on 0, so twelve must be last in this series.
faces=(
  🕐
  🕜
  🕑
  🕝
  🕒
  🕞
  🕓
  🕟
  🕔
  🕠
  🕕
  🕡
  🕖
  🕢
  🕗
  🕣
  🕘
  🕤
  🕙
  🕥
  🕚
  🕦
  🕛
  🕧
)

index=$(( (hour - 1) * 2 ))

# Depending on minutes, advance some steps.
# On minute 0..20, stay still on whole hour.
# On minute 20..50, go forwards one step (to half-past).
# On minute 50..59, go forwards two steps (to the next hour).
if [[ $minute -ge 50 ]]; then
  index=$((index + 2))
elif [[ $minute -ge 20 ]]; then
  index=$((index + 1))
fi

echo -n "${faces[$index]}"
