#!/usr/bin/env bash

root="$(dirname "$0")"
readarray -t boxes < <(mailboxes list)

trim() {
    local trimmed
    read -r trimmed

    # Strip leading space.
    trimmed="${trimmed## }"
    # Strip trailing space.
    trimmed="${trimmed%% }"

    echo "$trimmed"
}

for box_name in "${boxes[@]}"; do
  (
    set -e
    box="$(echo "$box_name" | cut -d "-" -f 1 | trim)"
    name="$(echo "$box_name" | cut -d "-" -f 2- | trim)"
    status="$(mailboxes status "$box")"
    icon="$(echo "$status" | cut -d " " -f 1)"
    unread="$(echo "$status" | cut -d " " -f 2)"

    text="${unread}"

    # If this computer has more than 1 mailbox, show the name of the mailbox
    # next to the counter so it's possible to see which mailbox has unread mail
    # in it.
    if [[ "${#boxes[@]}" -gt 1 ]]; then
      text="${text} (${name})"
    fi

    if [[ $unread -gt 0 ]]; then
      echo "$icon $text"
      echo -n " "
    fi
  )
done | trim
