#!/usr/bin/env bash

playing_icon=▶
paused_icon=⏸

root="$(dirname "$0")"

# shellcheck source=/home/mange/.local/share/gruvbox/colors.env
source "${XDG_DATA_HOME}/gruvbox/colors.env"

if player_status=$(playerctl status 2>/dev/null); then
  if [[ $player_status == "Paused" ]]; then
    playback_icon="$paused_icon"
  elif [[ $player_status == "Stopped" ]]; then
    playback_icon="${paused_icon}"
  else
    playback_icon="$playing_icon"
  fi

  artist="$(playerctl metadata artist 2>/dev/null)"
  title="$(playerctl metadata title 2>/dev/null)"

  if [[ ${#artist} -gt 30 ]]; then
    artist="${artist:0:29}…"
  fi

  if [[ ${#title} -gt 40 ]]; then
    title="${title:0:39}…"
  fi

  "$root/module" blue "${playback_icon}" "${artist} - ${title}"
else
  "$root/module" blue "${playing_icon}" ""
fi
