#!/usr/bin/env bash

playing_icon=
paused_icon=

# shellcheck source=/home/mange/.local/share/gruvbox/colors.env
source "${XDG_DATA_HOME}/gruvbox/colors.env"

if player_status=$(playerctl status 2>/dev/null); then
  before_text=""
  after_text=""

  if [[ $player_status == "Paused" ]]; then
    playback_icon="$paused_icon"
    before_text="%{F${dark4}}"
    after_text="%{F-}"
  elif [[ $player_status == "Stopped" ]]; then
    playback_icon="${paused_icon}"
  else
    playback_icon="$playing_icon"
  fi

  artist="$(playerctl metadata artist 2>/dev/null)"
  title="$(playerctl metadata title 2>/dev/null)"

  if [[ ${#artist} -gt 30 ]]; then
    artist="${artist:0:29}…"
  fi

  if [[ ${#title} -gt 40 ]]; then
    title="${title:0:39}…"
  fi

  echo "${before_text} ${playback_icon} ${artist} - ${title}${after_text}"
else
  echo "${play_icon}"
fi
