#!/usr/bin/env bash

# Usage: [color] [icon] [text…]

# shellsheck source=/home/mange/.local/share/gruvbox/colors.env
source ~/.local/share/gruvbox/colors.env

if [[ $# -lt 3 ]]; then
  echo "Must provide color name, icon part, and text" >&2
  exit 1
fi

base_color=${1}
icon=${2}
shift 2
text="${@}"

tmp="bright_${base_color}"
bright_color="${!tmp}"
tmp="neutral_${base_color}"
neutral_color="${!tmp}"
tmp="faded_${base_color}"
faded_color="${!tmp}"
unset tmp

function hexColorToRGBDecimal() {
  local color="${1:1}"
  echo "$((16#${color:0:2}))"
  echo "$((16#${color:2:2}))"
  echo "$((16#${color:4:2}))"
}

polybarFg="F"
polybarBg="B"
polybarColor() {
  fb="$1"
  color="$2"
  alpha="${3}"

  if [[ -n $alpha ]]; then
    alpha="#${alpha}"
    color="${color:1}"
  fi

  echo -n "%{${fb}${alpha}${color}}"
}

terminalFg=38
terminalBg=48
terminalColor() {
  fb=$1
  r=$2
  g=$3
  b=$4
  printf '\e[%d;2;%d;%d;%dm' "$fb" "$r" "$g" "$b"
}

rgb_bright=($(hexColorToRGBDecimal "$bright_color"))
rgb_faded=($(hexColorToRGBDecimal "$faded_color"))

if [[ -t 1 ]]; then
  terminalColor $terminalBg "${rgb_faded[@]}"
  echo -n " $icon "
  terminalColor $terminalBg "${rgb_bright[@]}"
  terminalColor $terminalFg 10 10 10
  echo -n " $text "
  tput sgr0
else
  polybarColor $polybarBg "$faded_color" "77"
  echo -n " $icon "
  polybarColor $polybarBg "$bright_color" "55"
  echo -n " $text "
  polybarColor $polybarBg "-"
fi
