#!/usr/bin/env bash
set -e

# shellcheck source=../gruvbox-colors.env
source ~/.gruvbox-colors.env

task_cmd="task rc.echo.command=no rc._forcecolor=no rc.blanklines=false rc.hooks=off rc.verbose=nothing"
task_cmd="$task_cmd rc.report.all.columns=id rc.report.all.labels=id"

ready=$($task_cmd +READY all | wc -l)
overdue=$($task_cmd +OVERDUE all | wc -l)
blocking=$($task_cmd +BLOCKING all | wc -l)
blocked=$($task_cmd +BLOCKED all | wc -l)
today=$($task_cmd +TODAY all | wc -l)
week=$($task_cmd +WEEK all | wc -l)

# {ready} [{today}/{week}] ({overdue} overdue), blockers: {blocking}->{blocked}

echo -n "${ready} [${today}/${week}]"
if [[ $overdue -gt 0 ]]; then
	echo -n " (%{F${bright_red}}${overdue} overdue%{F-})"
fi

if [[ $blocking -gt 0 || $blocked -gt 0 ]]; then
	echo -n ", blockers: %{F${bright_red}}${blocking}%{F-}→%{F${neutral_red}}${blocked}%{F-}"
fi
