#!/usr/bin/env bash
set -e

# shellcheck source=../../data/gruvbox/colors.env
source "${XDG_DATA_HOME}/gruvbox/colors.env"

task_cmd="task rc.echo.command=no rc._forcecolor=no rc.blanklines=false rc.hooks=off rc.verbose=nothing"
task_cmd="$task_cmd rc.report.scoped.columns=id rc.report.scoped.labels=id"

ready=$($task_cmd +READY scoped | wc -l)
overdue=$($task_cmd +OVERDUE scoped | wc -l)
blocking=$($task_cmd +BLOCKING scoped | wc -l)
blocked=$($task_cmd +BLOCKED scoped | wc -l)
today=$($task_cmd +TODAY scoped | wc -l)
week=$($task_cmd +WEEK scoped | wc -l)

# {ready} [{today}/{week}] ({overdue} overdue), blockers: {blocking}->{blocked}

echo -n "${ready} [${today}/${week}]"
if [[ $overdue -gt 0 ]]; then
	echo -n " (%{F${bright_red}}${overdue} overdue%{F-})"
fi

if [[ $blocking -gt 0 || $blocked -gt 0 ]]; then
	echo -n ", blockers: %{F${bright_red}}${blocking}%{F-}→%{F${neutral_red}}${blocked}%{F-}"
fi
