#!/usr/bin/env bash
set -e

root="$(dirname "$0")"

task_cmd="task rc.echo.command=no rc._forcecolor=no rc.blanklines=false rc.hooks=off rc.verbose=nothing"
task_cmd="$task_cmd rc.report.all.columns=id rc.report.all.labels=id"

ready=$($task_cmd +READY all | wc -l)
overdue=$($task_cmd +OVERDUE all | wc -l)
today=$($task_cmd +TODAY all | wc -l)
week=$($task_cmd +WEEK all | wc -l)

echo -n " ${today}/${week}/${ready}"

if [[ $overdue -gt 0 ]]; then
  echo -n " "
	echo -n " ${overdue}"
fi
