#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT
ctags --tag-relative -Rf.git/tags.$$ --exclude=.git --exclude=tmp --exclude=build --languages=-javascript,sql
mv .git/tags.$$ .git/tags
