# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json
- tags: fonts
  block:
    - name: Install important fonts
      when: ansible_os_family == "Archlinux"
      kewlfft.aur.aur:
        state: present
        name:
          - gnu-free-fonts # FreeMono; monospaced Unicode font. Popular in Kaomoji, etc.
          - noto-fonts # Android
      register: font_install_req

    - name: Install optional fonts
      when: ansible_os_family == "Archlinux"
      # Nothing here is super duper required
      ignore_errors: true
      kewlfft.aur.aur:
        state: present
        name:
          - ttf-jetbrains-mono
          - otf-overpass
          - ttf-nerd-fonts-symbols-1000-em-mono
          - noto-fonts-emoji # Emoji
          - noto-fonts-extra # etc.
          - ttf-ancient-fonts # Just because it is cool
          - ttf-dejavu
          - ttf-droid # Android
          - ttf-liberation # Arial, Times New Roman, etc.
          - ttf-monaco
          - ttf-roboto # Android
          # Eastern fonts, for Kaomoji, when opening Japanese websites, etc.
          - otf-ipafont # Japanese
          - ttf-arphic-uming # Chinese
          - ttf-baekmuk # Korean
          - ttf-indic-otf # Indic; includes ಠ_ಠ
      register: font_install_opt

    - name: Make sure fontconfig directory exists
      file:
        path: "{{ xdg_config_home }}/fontconfig/conf.d"
        state: directory

    - name: Install NerdFonts config
      when: ansible_os_family == "Archlinux"
      file:
        src: "/usr/share/fontconfig/conf.avail/10-nerd-font-symbols.conf"
        dest: "{{ xdg_config_home }}/fontconfig/conf.d/10-nerd-font-symbols.conf"
        state: link
        force: true
        follow: false
      register: nerdfont_config

    - name: Install fontconfig fallback
      file:
        src: 90-fallbacks.conf
        dest: "{{ xdg_config_home }}/fontconfig/conf.d/90-fallbacks.conf"
        state: link
        force: true
        follow: false
      register: font_fallbacks

    - name: Rebuild font cache
      when: nerdfont_config.changed or font_install_req.changed or font_install_opt.changed or font_fallbacks.changed
      command: fc-cache
